[package]
name = "mxtrix"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
bytes = "1"
rand = "0.8.4"
